"""
PPTX Exporter - Generates PowerPoint files from slide specifications and Gamma results.
Uses python-pptx library for PPTX generation.
"""
import io
import logging
import os
from datetime import datetime
from pathlib import Path
from typing import Optional

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RgbColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.enum.shapes import MSO_SHAPE

from app.models import SlideSpec, GammaSlideResult, SlideOutline

logger = logging.getLogger(__name__)


class PPTXExporter:
    """Exports slides to PowerPoint format."""

    def __init__(
        self,
        output_dir: Optional[str] = None,
        default_font: Optional[str] = None,
        title_font_size: Optional[int] = None,
        body_font_size: Optional[int] = None,
    ):
        self.output_dir = Path(output_dir or os.getenv("OUTPUT_DIR", "./output"))
        self.output_dir.mkdir(parents=True, exist_ok=True)

        self.default_font = default_font or os.getenv("DEFAULT_FONT", "Calibri")
        self.title_font_size = title_font_size or int(
            os.getenv("DEFAULT_FONT_SIZE_TITLE", "28")
        )
        self.body_font_size = body_font_size or int(
            os.getenv("DEFAULT_FONT_SIZE_BODY", "14")
        )
        self.margin = float(os.getenv("DEFAULT_MARGIN_INCHES", "0.5"))

        # Slide dimensions (standard 16:9)
        self.slide_width = Inches(13.33)
        self.slide_height = Inches(7.5)

        # Color scheme
        self.colors = {
            "primary": RgbColor(0x1A, 0x73, 0xE8),  # Blue
            "secondary": RgbColor(0x34, 0xA8, 0x53),  # Green
            "accent": RgbColor(0xFB, 0xBC, 0x05),  # Yellow
            "text": RgbColor(0x20, 0x21, 0x24),  # Dark gray
            "text_light": RgbColor(0x5F, 0x63, 0x68),  # Light gray
            "background": RgbColor(0xFF, 0xFF, 0xFF),  # White
            "success": RgbColor(0x4C, 0xAF, 0x50),  # Green
            "warning": RgbColor(0xFF, 0x98, 0x00),  # Orange
            "error": RgbColor(0xF4, 0x43, 0x36),  # Red
        }

        logger.info(f"PPTXExporter initialized. Output dir: {self.output_dir}")

    def create_presentation(
        self,
        deck_title: str,
        slides_data: list[tuple[SlideSpec, GammaSlideResult]],
        author: str = "Slide Creator",
        subtitle: Optional[str] = None,
    ) -> str:
        """
        Create a complete PPTX presentation.

        Args:
            deck_title: Title of the presentation
            slides_data: List of (SlideSpec, GammaSlideResult) tuples
            author: Author name for metadata
            subtitle: Optional subtitle

        Returns:
            Path to the generated PPTX file
        """
        prs = Presentation()

        # Set slide dimensions (16:9)
        prs.slide_width = self.slide_width
        prs.slide_height = self.slide_height

        # Set metadata
        prs.core_properties.title = deck_title
        prs.core_properties.author = author
        prs.core_properties.created = datetime.now()
        prs.core_properties.modified = datetime.now()
        prs.core_properties.subject = "Generated by Slide Creator"

        # Add title slide
        self._add_title_slide(prs, deck_title, subtitle, author)

        # Add content slides
        for spec, gamma_result in slides_data:
            if gamma_result and gamma_result.success:
                self._add_slide_from_gamma(prs, spec, gamma_result)
            else:
                # Fallback: create slide from spec only
                self._add_slide_from_spec(prs, spec)

        # Generate filename and save
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_title = "".join(c for c in deck_title[:30] if c.isalnum() or c in " _-").strip()
        safe_title = safe_title.replace(" ", "_")
        filename = f"{timestamp}_{safe_title}.pptx"
        filepath = self.output_dir / filename

        prs.save(str(filepath))
        logger.info(f"Presentation saved: {filepath}")

        return str(filepath)

    def _add_title_slide(
        self,
        prs: Presentation,
        title: str,
        subtitle: Optional[str],
        author: str,
    ) -> None:
        """Add the title slide."""
        slide_layout = prs.slide_layouts[6]  # Blank layout
        slide = prs.slides.add_slide(slide_layout)

        # Title
        title_box = slide.shapes.add_textbox(
            Inches(self.margin),
            Inches(2.5),
            self.slide_width - Inches(self.margin * 2),
            Inches(1.5),
        )
        title_frame = title_box.text_frame
        title_para = title_frame.paragraphs[0]
        title_para.text = title
        title_para.font.size = Pt(44)
        title_para.font.bold = True
        title_para.font.name = self.default_font
        title_para.font.color.rgb = self.colors["text"]
        title_para.alignment = PP_ALIGN.CENTER

        # Subtitle
        if subtitle:
            subtitle_box = slide.shapes.add_textbox(
                Inches(self.margin),
                Inches(4.0),
                self.slide_width - Inches(self.margin * 2),
                Inches(0.8),
            )
            subtitle_frame = subtitle_box.text_frame
            subtitle_para = subtitle_frame.paragraphs[0]
            subtitle_para.text = subtitle
            subtitle_para.font.size = Pt(24)
            subtitle_para.font.name = self.default_font
            subtitle_para.font.color.rgb = self.colors["text_light"]
            subtitle_para.alignment = PP_ALIGN.CENTER

        # Author and date
        meta_box = slide.shapes.add_textbox(
            Inches(self.margin),
            Inches(6.5),
            self.slide_width - Inches(self.margin * 2),
            Inches(0.5),
        )
        meta_frame = meta_box.text_frame
        meta_para = meta_frame.paragraphs[0]
        meta_para.text = f"{author} | {datetime.now().strftime('%B %Y')}"
        meta_para.font.size = Pt(12)
        meta_para.font.name = self.default_font
        meta_para.font.color.rgb = self.colors["text_light"]
        meta_para.alignment = PP_ALIGN.CENTER

    def _add_slide_from_gamma(
        self,
        prs: Presentation,
        spec: SlideSpec,
        gamma_result: GammaSlideResult,
    ) -> None:
        """Add a slide using Gamma's structured content."""
        slide_layout = prs.slide_layouts[6]  # Blank layout
        slide = prs.slides.add_slide(slide_layout)

        content = gamma_result.structured_content or {}
        elements = content.get("elements", [])

        # If we have a Gamma image, use it as background
        if gamma_result.image_data:
            self._add_image_background(slide, gamma_result.image_data)
            return

        # Otherwise, recreate from structured content
        for element in elements:
            self._add_element_to_slide(slide, element)

        # If no elements from Gamma, fall back to spec
        if not elements:
            self._add_slide_content_from_spec(slide, spec)

    def _add_slide_from_spec(self, prs: Presentation, spec: SlideSpec) -> None:
        """Add a slide directly from SlideSpec (fallback when Gamma unavailable)."""
        slide_layout = prs.slide_layouts[6]  # Blank layout
        slide = prs.slides.add_slide(slide_layout)
        self._add_slide_content_from_spec(slide, spec)

    def _add_slide_content_from_spec(self, slide, spec: SlideSpec) -> None:
        """Add content to slide from SlideSpec."""
        margin = Inches(self.margin)
        content_width = self.slide_width - (margin * 2)

        # Title
        title_box = slide.shapes.add_textbox(
            margin, margin, content_width, Inches(0.6)
        )
        title_frame = title_box.text_frame
        title_para = title_frame.paragraphs[0]
        title_para.text = spec.title
        title_para.font.size = Pt(self.title_font_size)
        title_para.font.bold = True
        title_para.font.name = self.default_font
        title_para.font.color.rgb = self.colors["text"]

        # Framework indicator (small tag)
        tag_box = slide.shapes.add_textbox(
            self.slide_width - Inches(2.5),
            margin,
            Inches(2),
            Inches(0.3),
        )
        tag_frame = tag_box.text_frame
        tag_para = tag_frame.paragraphs[0]
        tag_para.text = spec.framework_name
        tag_para.font.size = Pt(8)
        tag_para.font.name = self.default_font
        tag_para.font.color.rgb = self.colors["text_light"]
        tag_para.alignment = PP_ALIGN.RIGHT

        # Headline
        headline_box = slide.shapes.add_textbox(
            margin, Inches(1.0), content_width, Inches(0.5)
        )
        headline_frame = headline_box.text_frame
        headline_para = headline_frame.paragraphs[0]
        headline_para.text = spec.copy.headline
        headline_para.font.size = Pt(18)
        headline_para.font.bold = True
        headline_para.font.name = self.default_font
        headline_para.font.color.rgb = self.colors["primary"]

        # Add framework-specific layout
        self._add_framework_layout(slide, spec)

        # Body bullets
        if spec.copy.body:
            body_top = Inches(4.5)
            body_box = slide.shapes.add_textbox(
                margin, body_top, content_width, Inches(2.0)
            )
            body_frame = body_box.text_frame
            body_frame.word_wrap = True

            for i, bullet in enumerate(spec.copy.body[:5]):
                if i == 0:
                    para = body_frame.paragraphs[0]
                else:
                    para = body_frame.add_paragraph()
                para.text = f"• {bullet}"
                para.font.size = Pt(self.body_font_size)
                para.font.name = self.default_font
                para.font.color.rgb = self.colors["text"]
                para.space_after = Pt(6)

        # Footnotes
        if spec.copy.footnotes:
            footnote_box = slide.shapes.add_textbox(
                margin,
                self.slide_height - Inches(0.6),
                content_width,
                Inches(0.4),
            )
            footnote_frame = footnote_box.text_frame
            footnote_para = footnote_frame.paragraphs[0]
            footnote_para.text = " | ".join(spec.copy.footnotes)
            footnote_para.font.size = Pt(8)
            footnote_para.font.name = self.default_font
            footnote_para.font.color.rgb = self.colors["text_light"]

        # Add speaker notes if present
        if spec.copy.speaker_notes:
            notes_slide = slide.notes_slide
            notes_frame = notes_slide.notes_text_frame
            notes_frame.text = spec.copy.speaker_notes

    def _add_framework_layout(self, slide, spec: SlideSpec) -> None:
        """Add framework-specific visual layout elements."""
        framework = spec.framework_id
        margin = Inches(self.margin)
        content_top = Inches(1.6)
        content_height = Inches(2.8)
        content_width = self.slide_width - (margin * 2)

        if framework == "2x2_matrix":
            self._add_2x2_matrix(slide, spec, margin, content_top, content_width, content_height)
        elif framework == "scr":
            self._add_three_columns(
                slide, spec, margin, content_top, content_width, content_height,
                ["Situation", "Complication", "Resolution"]
            )
        elif framework == "before_after_bridge":
            self._add_three_columns(
                slide, spec, margin, content_top, content_width, content_height,
                ["Before", "After", "Bridge"]
            )
        elif framework == "pros_cons_tradeoff":
            self._add_two_columns(
                slide, spec, margin, content_top, content_width, content_height,
                ["Pros", "Cons"], [self.colors["success"], self.colors["error"]]
            )
        elif framework == "funnel":
            self._add_funnel(slide, spec, margin, content_top, content_width, content_height)
        elif framework == "timeline_roadmap":
            self._add_timeline(slide, spec, margin, content_top, content_width, content_height)
        elif framework == "kpi_scorecard":
            self._add_kpi_scorecard(slide, spec, margin, content_top, content_width, content_height)
        else:
            # Default: content sections as boxes
            self._add_content_sections(slide, spec, margin, content_top, content_width, content_height)

    def _add_2x2_matrix(self, slide, spec, left, top, width, height):
        """Add 2x2 matrix layout."""
        cell_width = width / 2 - Inches(0.1)
        cell_height = height / 2 - Inches(0.1)

        quadrants = [
            (left, top, "High/Low"),
            (left + cell_width + Inches(0.2), top, "High/High"),
            (left, top + cell_height + Inches(0.2), "Low/Low"),
            (left + cell_width + Inches(0.2), top + cell_height + Inches(0.2), "Low/High"),
        ]

        sections = spec.layout.sections[:4] if spec.layout.sections else []

        for i, (x, y, default_label) in enumerate(quadrants):
            shape = slide.shapes.add_shape(
                MSO_SHAPE.ROUNDED_RECTANGLE, x, y, cell_width, cell_height
            )
            shape.fill.solid()
            shape.fill.fore_color.rgb = RgbColor(0xF5, 0xF5, 0xF5)
            shape.line.color.rgb = self.colors["primary"]

            # Add label
            label = sections[i].name if i < len(sections) else default_label
            content = sections[i].content if i < len(sections) else ""

            tf = shape.text_frame
            tf.word_wrap = True
            p = tf.paragraphs[0]
            p.text = label
            p.font.size = Pt(10)
            p.font.bold = True
            p.font.name = self.default_font
            p.alignment = PP_ALIGN.CENTER

            if content:
                p2 = tf.add_paragraph()
                p2.text = content[:100]
                p2.font.size = Pt(9)
                p2.font.name = self.default_font
                p2.alignment = PP_ALIGN.CENTER

    def _add_three_columns(self, slide, spec, left, top, width, height, labels):
        """Add three-column layout."""
        col_width = width / 3 - Inches(0.15)
        sections = spec.layout.sections[:3] if spec.layout.sections else []

        for i, label in enumerate(labels):
            x = left + (i * (col_width + Inches(0.2)))

            shape = slide.shapes.add_shape(
                MSO_SHAPE.ROUNDED_RECTANGLE, x, top, col_width, height
            )
            shape.fill.solid()
            colors = [
                RgbColor(0xE3, 0xF2, 0xFD),
                RgbColor(0xFF, 0xEB, 0xEE),
                RgbColor(0xE8, 0xF5, 0xE9),
            ]
            shape.fill.fore_color.rgb = colors[i % 3]
            shape.line.color.rgb = self.colors["primary"]

            tf = shape.text_frame
            tf.word_wrap = True
            tf.margin_left = Inches(0.1)
            tf.margin_right = Inches(0.1)
            tf.margin_top = Inches(0.1)

            p = tf.paragraphs[0]
            p.text = label
            p.font.size = Pt(12)
            p.font.bold = True
            p.font.name = self.default_font
            p.alignment = PP_ALIGN.CENTER

            if i < len(sections):
                p2 = tf.add_paragraph()
                p2.text = sections[i].content[:150]
                p2.font.size = Pt(9)
                p2.font.name = self.default_font

    def _add_two_columns(self, slide, spec, left, top, width, height, labels, colors):
        """Add two-column layout."""
        col_width = width / 2 - Inches(0.1)
        sections = spec.layout.sections[:2] if spec.layout.sections else []

        for i, (label, color) in enumerate(zip(labels, colors)):
            x = left + (i * (col_width + Inches(0.2)))

            shape = slide.shapes.add_shape(
                MSO_SHAPE.ROUNDED_RECTANGLE, x, top, col_width, height
            )
            shape.fill.solid()
            bg_colors = [RgbColor(0xE8, 0xF5, 0xE9), RgbColor(0xFF, 0xEB, 0xEE)]
            shape.fill.fore_color.rgb = bg_colors[i]
            shape.line.color.rgb = color

            tf = shape.text_frame
            tf.word_wrap = True

            p = tf.paragraphs[0]
            p.text = label
            p.font.size = Pt(14)
            p.font.bold = True
            p.font.name = self.default_font
            p.font.color.rgb = color
            p.alignment = PP_ALIGN.CENTER

            if i < len(sections):
                p2 = tf.add_paragraph()
                p2.text = sections[i].content[:200]
                p2.font.size = Pt(10)
                p2.font.name = self.default_font

    def _add_funnel(self, slide, spec, left, top, width, height):
        """Add funnel visualization."""
        sections = spec.layout.sections or []
        num_stages = min(len(sections), 5) if sections else 4

        stage_height = height / num_stages
        center_x = left + width / 2

        for i in range(num_stages):
            # Funnel narrows as it goes down
            stage_width = width * (1 - i * 0.15)
            x = center_x - stage_width / 2

            shape = slide.shapes.add_shape(
                MSO_SHAPE.CHEVRON,
                x,
                top + (i * stage_height),
                stage_width,
                stage_height - Inches(0.05),
            )
            shape.fill.solid()
            # Gradient from light to dark blue
            shade = int(0xE3 - (i * 0x20))
            shape.fill.fore_color.rgb = RgbColor(shade, shade, 0xFD)
            shape.line.color.rgb = self.colors["primary"]

            tf = shape.text_frame
            p = tf.paragraphs[0]
            if i < len(sections):
                p.text = sections[i].name
            else:
                p.text = f"Stage {i + 1}"
            p.font.size = Pt(10)
            p.font.bold = True
            p.font.name = self.default_font
            p.alignment = PP_ALIGN.CENTER

    def _add_timeline(self, slide, spec, left, top, width, height):
        """Add timeline visualization."""
        sections = spec.layout.sections or []
        num_points = min(len(sections), 6) if sections else 4

        # Horizontal line
        line = slide.shapes.add_shape(
            MSO_SHAPE.RECTANGLE,
            left,
            top + height / 2 - Inches(0.02),
            width,
            Inches(0.04),
        )
        line.fill.solid()
        line.fill.fore_color.rgb = self.colors["primary"]
        line.line.fill.background()

        # Milestone points
        point_spacing = width / (num_points + 1)

        for i in range(num_points):
            x = left + point_spacing * (i + 1)

            # Circle marker
            circle = slide.shapes.add_shape(
                MSO_SHAPE.OVAL,
                x - Inches(0.15),
                top + height / 2 - Inches(0.15),
                Inches(0.3),
                Inches(0.3),
            )
            circle.fill.solid()
            circle.fill.fore_color.rgb = self.colors["primary"]
            circle.line.color.rgb = self.colors["primary"]

            # Label above/below alternating
            label_y = top + Inches(0.2) if i % 2 == 0 else top + height - Inches(0.6)

            label_box = slide.shapes.add_textbox(
                x - Inches(0.6), label_y, Inches(1.2), Inches(0.4)
            )
            tf = label_box.text_frame
            p = tf.paragraphs[0]
            if i < len(sections):
                p.text = sections[i].name
            else:
                p.text = f"Q{i + 1}"
            p.font.size = Pt(9)
            p.font.bold = True
            p.font.name = self.default_font
            p.alignment = PP_ALIGN.CENTER

    def _add_kpi_scorecard(self, slide, spec, left, top, width, height):
        """Add KPI scorecard visualization."""
        sections = spec.layout.sections or []
        num_kpis = min(len(sections), 6) if sections else 3

        cols = 3
        rows = (num_kpis + cols - 1) // cols

        kpi_width = width / cols - Inches(0.1)
        kpi_height = height / rows - Inches(0.1)

        for i in range(num_kpis):
            row = i // cols
            col = i % cols

            x = left + col * (kpi_width + Inches(0.1))
            y = top + row * (kpi_height + Inches(0.1))

            shape = slide.shapes.add_shape(
                MSO_SHAPE.ROUNDED_RECTANGLE, x, y, kpi_width, kpi_height
            )
            shape.fill.solid()
            shape.fill.fore_color.rgb = RgbColor(0xF5, 0xF5, 0xF5)
            shape.line.color.rgb = self.colors["success"]

            tf = shape.text_frame
            tf.word_wrap = True

            p = tf.paragraphs[0]
            if i < len(sections):
                p.text = sections[i].name
            else:
                p.text = f"KPI {i + 1}"
            p.font.size = Pt(10)
            p.font.bold = True
            p.font.name = self.default_font
            p.alignment = PP_ALIGN.CENTER

            # Value
            p2 = tf.add_paragraph()
            if i < len(sections):
                p2.text = sections[i].content[:50]
            else:
                p2.text = "—"
            p2.font.size = Pt(20)
            p2.font.bold = True
            p2.font.color.rgb = self.colors["primary"]
            p2.alignment = PP_ALIGN.CENTER

    def _add_content_sections(self, slide, spec, left, top, width, height):
        """Add generic content sections."""
        sections = spec.layout.sections
        if not sections:
            return

        num_sections = min(len(sections), 4)
        section_width = width / num_sections - Inches(0.1)

        for i, section in enumerate(sections[:num_sections]):
            x = left + i * (section_width + Inches(0.1))

            shape = slide.shapes.add_shape(
                MSO_SHAPE.ROUNDED_RECTANGLE, x, top, section_width, height
            )
            shape.fill.solid()
            shape.fill.fore_color.rgb = RgbColor(0xF8, 0xF9, 0xFA)
            shape.line.color.rgb = self.colors["primary"]

            tf = shape.text_frame
            tf.word_wrap = True
            tf.margin_left = Inches(0.1)
            tf.margin_right = Inches(0.1)
            tf.margin_top = Inches(0.1)

            p = tf.paragraphs[0]
            p.text = section.name
            p.font.size = Pt(11)
            p.font.bold = True
            p.font.name = self.default_font

            p2 = tf.add_paragraph()
            p2.text = section.content[:200]
            p2.font.size = Pt(9)
            p2.font.name = self.default_font

    def _add_element_to_slide(self, slide, element: dict) -> None:
        """Add a single element from Gamma's structured content to the slide."""
        elem_type = element.get("type")
        role = element.get("role")
        position = element.get("position", {})

        x = Inches(position.get("x", 50) / 192)  # Convert from pixels
        y = Inches(position.get("y", 50) / 144)
        w = Inches(position.get("width", 500) / 192)
        h = Inches(position.get("height", 100) / 144)

        if elem_type == "text":
            box = slide.shapes.add_textbox(x, y, w, h)
            tf = box.text_frame
            tf.word_wrap = True
            p = tf.paragraphs[0]
            p.text = element.get("content", "")

            style = element.get("style", {})
            p.font.size = Pt(style.get("fontSize", 14))
            p.font.name = self.default_font
            if style.get("fontWeight") == "bold":
                p.font.bold = True
            if role == "title":
                p.font.size = Pt(self.title_font_size)
                p.font.bold = True

        elif elem_type == "shape":
            # Add shape placeholder
            shape = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, x, y, w, h)
            shape.fill.solid()
            shape.fill.fore_color.rgb = RgbColor(0xF0, 0xF0, 0xF0)

            if element.get("label"):
                tf = shape.text_frame
                p = tf.paragraphs[0]
                p.text = element.get("label", "")
                p.font.size = Pt(10)
                p.alignment = PP_ALIGN.CENTER

    def _add_image_background(self, slide, image_data: bytes) -> None:
        """Add image as slide background."""
        image_stream = io.BytesIO(image_data)
        slide.shapes.add_picture(
            image_stream,
            Inches(0),
            Inches(0),
            width=self.slide_width,
            height=self.slide_height,
        )

    def export_session(
        self,
        session_id: str,
        deck_title: str,
        slides_data: list[tuple[SlideSpec, GammaSlideResult]],
        author: str = "Slide Creator",
        subtitle: Optional[str] = None,
    ) -> str:
        """
        Export a complete session to PPTX.

        Args:
            session_id: Session identifier (used in filename)
            deck_title: Presentation title
            slides_data: List of (SlideSpec, GammaSlideResult) tuples
            author: Author name
            subtitle: Optional subtitle

        Returns:
            Path to generated PPTX file
        """
        filepath = self.create_presentation(
            deck_title=deck_title,
            slides_data=slides_data,
            author=author,
            subtitle=subtitle,
        )

        # Also save with session ID for easy reference
        session_path = self.output_dir / f"{session_id}.pptx"
        if not session_path.exists():
            import shutil
            shutil.copy(filepath, session_path)

        return filepath
